apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio-repo
  namespace: istio-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 1h
