apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      version: "~1.23"
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  interval: 5m
  values:
    global:
      externalIstiod: false
      istioNamespace: istio-system
      mountMtlsCerts: false
      pilotCertProvider: istiod
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        image: proxyv2
        tag: 1.23.2
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      cpu:
        targetAverageUtilization: 80
      replicaCount: 1
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: true
