apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cluster-kustomization

resources:
  # System Resources
  - ../../overlays/system/istio
  - ../../overlays/system/kiali
  # Application Resources
  - ../../overlays/applications/vtt-maps
