apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: istio-system
spec:
  releaseName: kiali-operator
  interval: 5m0s
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali-repo
        namespace: istio-system
      version: "*"
  values:
    nameOverride: ""
    fullnameOverride: ""

    image:
      repo: quay.io/kiali/kiali-operator
      pullPolicy: IfNotPresent # Updated to IfNotPresent for optimization
    resources:
      requests:
        cpu: "50m" # Increased CPU request for better performance
        memory: "128Mi" # Increased memory for better handling
      limits:
        cpu: "200m" # Optional: set CPU limit to control resource usage
        memory: "256Mi" # Optional: set memory limit for safety

    metrics:
      enabled: true

    debug:
      enabled: true
      verbosity: "1"
      enableProfiler: false

    onlyViewOnlyMode: false
    allowAdHocKialiNamespace: true
    allowAdHocKialiImage: false
    allowAdHocOSSMConsoleImage: false
    allowSecurityContextOverride: false
    allowAllAccessibleNamespaces: true

    cr:
      create: true
      namespace: istio-system
      spec:
        auth:
          strategy: anonymous
        deployment:
          accessible_namespaces:
            - "**"
