apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      version: "~1.23"
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: istio-system
  interval: 5m
  values:
    base:
      enableCRDTemplates: false
      enableIstioConfigCRDs: true
    defaultRevision: default
    experimental: {}
