apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vtt-maps-tls-cert
  namespace: vtt-maps
spec:
  secretName: vtt-maps-tls-secret
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: vtt-maps.dnd-apps.dev

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
    rotationPolicy: Always

  isCA: false
  usages:
    - server auth
    - client auth

  dnsNames:
    - vtt-maps.dnd-apps.dev

  additionalOutputFormats:
    - type: CombinedPEM # PEM private key and cert chain combined
