apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtt-maps
  namespace: vtt-maps
  labels:
    app: vtt-maps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtt-maps
  template:
    metadata:
      labels:
        app: vtt-maps
    spec:
      containers:
        - name: vtt-maps
          image: mbround18/vtt-maps:static-site
          imagePullPolicy: Always # Ensures always pulling the latest version of the tag
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-certificates
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: tls-certificates
          secret:
            secretName: vtt-maps-tls-secret
