apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vtt-maps
  namespace: flux-system
spec:
  interval: 5m
  path: "."
  prune: true
  sourceRef:
    kind: GitRepository
    name: vtt-maps
    namespace: flux-system
  targetNamespace: vtt-maps
  images:
    - name: mbround18/vtt-maps
      newTag: "$(vtt-maps-policy)"
