apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: vtt-maps-gateway
  namespace: vtt-maps
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "vtt-maps.dnd-apps.dev"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "vtt-maps.dnd-apps.dev"
      tls:
        credentialName: vtt-maps-tls-secret
        mode: SIMPLE
