apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vtt-maps
  namespace: vtt-maps
spec:
  hosts: &hosts
    - "vtt-maps.dnd-apps.dev"
  gateways:
    - vtt-maps-gateway
  tls:
    - match:
        - port: 443
          sniHosts: *hosts
      route:
        - destination:
            host: vtt-maps
            port:
              number: 443
